# Generated by Django 5.0.6 on 2024-06-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adltest',
            name='campo1',
            field=models.CharField(max_length=101),
        ),
    ]
