# Generated by Django 5.0.6 on 2024-06-13 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_alter_adltest_campo1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adltest',
        ),
    ]
